### ISSUE TITLE
Handle whitespaces in source files' path

### ISSUE THREAD

**Issue by White-Oak** [saviorisdead/RustyCode#59] opened 2015-12-30 18:39 UTC
I tried to enclose paths in suggestService.js with quotes to no avail.

Error output:
```
Last command: 
find-definition 5 45 "/data/Users/White Oak/test-project/src/parser.rs" /tmp/tmp-9430Dk1ZV1yxflVR.tmp

Racer Output: 

Racer Error: 
[1;31merror: Found argument '/tmp/tmp-9430Dk1ZV1yxflVR.tmp', but find-definition wasn't expecting any

USAGE:
	find-definition <linenum> <charnum> <path> [substitute_file]

For more information try --help
```
This error does not show up when using the extension with the same project moved to a location with no spaces.

**Comment by Draivin** [comment] 2015-12-31 00:59
This was a limitation on the last version of `racer`, the new version has support for it, but it still has not been integrated into Rusty Code.

Duplicate of #45.

**Closed** 2015-12-31 01:37 UTC
